name: golang-build

on:
  push:
    paths:
      - ".github/workflows/golang-build.yml"
      - "golang/**"
  workflow_dispatch:

jobs:
  build:
    name: Build Go Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.3' # Specify the Go version to use
      - name: Build
        run: go build -o myapp ./golang/hello-world
      - name: Run Tests
        run: go test ./golang/...